### ISSUE TITLE
Node 18 compatiblity

### ISSUE THREAD

**Issue by tnajdek** [zotero/pdf-worker#18]
Node 18 is now the [active LTS version](https://github.com/nodejs/Release) however the build will fail with Node >=18. This is caused by webpack, inside pdf.js module, which is old and [depends on a legacy hashing algorithm](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported).

The workaround is to either switch to Node 16 or build with `NODE_OPTIONS=--openssl-legacy-provider` but it would be nice to update dependencies in pdf.js submodule.

**Comment by iago-pssjd** [comment]
Current versions of pdf.js seem to support Node 18: https://github.com/mozilla/pdf.js/issues/16403
